s=set()
s.add(int(input("\nEnter Number 1 : ")))
s.add(int(input("\nEnter Number 2 : ")))
s.add(int(input("\nEnter Number 3 : ")))
s.add(int(input("\nEnter Number 4 : ")))
s.add(int(input("\nEnter Number 5 : ")))
s.add(int(input("\nEnter Number 6 : ")))
s.add(int(input("\nEnter Number 7 : ")))
s.add(int(input("\nEnter Number 8 : ")))
print("\nUnique Numbers are :",s)